### ISSUE TITLE
Request: Highlights with Show Game Titles disabled.

### ISSUE THREAD

**Issue by lechuck01** [FaithLV/WPF_Spectabis#14]
Would it be possible to add the coloured highlight feature when selecting games when the Show Game Titles option is disabled? I think it would be helpful as without it I find that sometimes when I double click on a game I'm unsure of whether its loading or not and having it highlighted is a good indicator.

**Comment by FaithLV** [comment]
I'll see what I can do, but no promises.
Spectabis should minimize itself when a game is launcher though.

**Comment by lechuck01** [comment]
You're right, it does minimize when you launch a game, I just thought it would be helpful because there's a few seconds delay (like 15-20 seconds) before pcsx2 opens after clicking a game and the mouse pointer doesn't show the loading animation either.
