### ISSUE TITLE
Spectabis changes plugins

### ISSUE THREAD

**Issue by Silent-Hunter** [FaithLV/WPF_Spectabis#16]
Sorry for the odd title, I wasn't sure what else to call this.

Basically, when I run Katamari Damacy via Spectabis, the guy singing "Na na na na na na" never stops, but when I run it from regular PCSX2, it works fine. I also noticed Spectabis uses its own plugin files, not the regular PCSX2 ones.

The following two screenshots show a peculiar difference between Spectabis' audio config, and PCSX2's one.

I can't help but wonder if this is why the problem is occuring.

![pcsx2](https://user-images.githubusercontent.com/3732535/30461169-35965450-9971-11e7-8d62-75722814a345.png)
![spectabis](https://user-images.githubusercontent.com/3732535/30461170-359ff320-9971-11e7-9de1-29e59089d047.png)

**Comment by Silent-Hunter** [comment]
Forgot to add, using version 1.0.6465.31861

**Comment by FaithLV** [comment]
Spectabis doesn't change any plugins, but uses plugins from it's own folder, because people had problems with importing plugins the PCSX2 folder.

Those plugins are only used to configure plugins, they are not used in emulation.

Other than that, I have no idea why it happens. I'll ask around.
