### ISSUE TITLE
Spectabis wants to re-add Games

### ISSUE THREAD

**Issue by Amsee-Daniel** [FaithLV/WPF_Spectabis#19]
When I launch Spectabis, it alway informs me about "new" games in my directory

**Comment by FaithLV** [comment]
Please don't close unresolved issues. 
Just because I don't respond doesn't mean I don't read them.

**Comment by Amsee-Daniel** [comment]
Sorry, i thought, i misunderstood the "Add Directory" Option.
Using it as a "bulk add" feature rather than a library-Folder Feature fixed it for me. I thought that was the intention of this Option all along.
