### ISSUE TITLE
Spectabis-WPF stopped working

### ISSUE THREAD

**Issue by diprotic** [FaithLV/WPF_Spectabis#22]
I have .NET framework 4.5 (or higher according to windows) so I'm not too sure what causes Spectabis to crash with, "Spectabis=WPF stopped working".

I've noticed that I have to use the program slowly otherwise it'll crash. Too many clicks or clicking different buttons like the back arrow or menu config button too fast will cause it to crash.

What can we do about it?

**Comment by FaithLV** [comment]
Not sure. I've never really encountered any random crashes.

**Comment by LeRoy3rd** [comment]
I'm having the same issue... I've been using it for about a week, today I purchased a couple new games, went to add them, and every time I do, instant crash. I removed the program, and the config files, and started from scratch. Now I can't even load the games I had previously, it just crashes with the Spectabis-WPF error. What can I do to help? Could you use logs or a video screencap showing the error? At this point, I can't use it at all. :'((

Thanks,
LeRoy3rd

**Comment by LeRoy3rd** [comment]
It's been almost a week since I posted, with no response... Before I posted, I scoured the internet to try to find a solution (with no success). Should I post about this somewhere else?

-LeRoy3rd

**Comment by LeRoy3rd** [comment]
Thank you so much for the response! I didn't even know this HAD console output! <3

Upon running it in console mode, I found the problem fairly quickly:
It was looking for a directory called "inis" in user/Documents/PCSX2, but the folder it had was named inis_1.4.0.

I made a copy of the folder, renamed it ti "inis", ran the program again, and it worked (kind of)!

The first game I tried to add was a new one, and it worked flawlessly, the next one had been added earlier, and caused a crash. A separate but identical error. This time the error said there was an erro writing to a config folder for a specific game. I navigated to the folder, renamed it, made a copy and deleted the current configs. Now it works again.

Not sure what changed to cause these errors, but, in the very least, this description may help others running into the same problem.

Thanks again for putting me onto the right track. Do you have a Patreon account (or some other way) so I can buy you a beer?

-LeRoy3rd

**Comment by FaithLV** [comment]
Glad you got it running! :)
