### ISSUE TITLE
Very Ram Hungry

### ISSUE THREAD

**Issue by RinMaru** [FaithLV/WPF_Spectabis#25]
Im not sure if this is an issue or is intended but ive seen this program take up about 2gb of ram. seems a bit much for a frontend

Windows 10 x64
i5 6402P 8GB DDR4
AMD RX 480 4GB

**Comment by FaithLV** [comment]
Never had a library anywhere near that size, but that still sounds way too much. 

Could you tell me the size of your Resources/Configs folder? It could be that all the images loaded really do take up that size.

**Comment by FaithLV** [comment]
Could you archive your Resources/Configs folder and upload it somewhere so I can test? Don't worry, it doesn't include any personal information other than game file path.

**Comment by RinMaru** [comment]
ill upload it to Google Drive

**Comment by RinMaru** [comment]
https://drive.google.com/open?id=1bo2cCk-S076OPm_oiDVwHIjRaski7PPd

**Comment by FaithLV** [comment]
Thanks! 2GB indeed!

Looks like there's a memory leak in unmanaged code sections, I'll try to find the cause of it.

**Comment by FaithLV** [comment]
Issue has been fixed in https://github.com/FaithLV/WPF_Spectabis/commit/ee07b4b3ce520567d761eb0da7f1eceb3804cbda

I have one more idea to improve performance and you should expect an updated release in upcoming days.

**Comment by RinMaru** [comment]
awesome thanks ^^ I look forward to the update

**Comment by FaithLV** [comment]
Here's the update!
https://github.com/FaithLV/WPF_Spectabis/releases/tag/1.0.8

**Comment by RinMaru** [comment]
awesome works like a charm
